# Generated by Django 3.2.16 on 2023-01-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_usersetting_verification_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
