# Generated by Django 3.2.16 on 2023-01-15 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20230115_1446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAbonn',
        ),
    ]
