# Generated by Django 3.2.16 on 2023-01-15 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_userabonn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userabonn',
            old_name='user',
            new_name='chaine',
        ),
    ]
