# Generated by Django 3.2.16 on 2023-01-16 20:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_rename_user_userabonn_chaine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userabonn',
            name='abonnements',
        ),
        migrations.AddField(
            model_name='userabonn',
            name='abonnements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonnements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='verification_expires',
            field=models.DateField(default=datetime.date(2023, 1, 19)),
        ),
    ]
