# Generated by Django 3.2.16 on 2023-01-16 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20230116_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userabonn',
            name='abonnements',
        ),
        migrations.AddField(
            model_name='userabonn',
            name='abonnements',
            field=models.ManyToManyField(blank=True, null=True, related_name='abonnements', to=settings.AUTH_USER_MODEL),
        ),
    ]
