# Generated by Django 3.2.16 on 2023-01-18 22:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_usersetting_verification_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userabonn',
            name='abonnements',
            field=models.ManyToManyField(blank=True, related_name='abonnements', to=settings.AUTH_USER_MODEL),
        ),
    ]
