# Generated by Django 3.2.16 on 2023-01-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='desc_playlist',
            field=models.CharField(default=False, max_length=512),
        ),
    ]
