# Generated by Django 3.2.16 on 2023-01-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_playlist_desc_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='miniature_playlist',
            field=models.ImageField(blank=True, null=True, upload_to='PlayListImg'),
        ),
    ]
