# Generated by Django 3.2.16 on 2023-01-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_playlist_miniature_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='miniature_playlist',
            field=models.ImageField(blank=True, null=True, upload_to='playlist_img'),
        ),
    ]
