# Generated by Django 3.2.16 on 2023-01-21 11:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_alter_playlist_miniature_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='desc_playlist',
            field=models.CharField(blank=True, default=False, max_length=512),
        ),
        migrations.AlterField(
            model_name='userabonn',
            name='chaine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='verification_expires',
            field=models.DateField(default=datetime.date(2023, 1, 24)),
        ),
    ]
