# Generated by Django 3.2.16 on 2023-01-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_alter_usersetting_verification_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='miniature_playlist',
            field=models.FileField(blank=True, null=True, upload_to='playlist_img'),
        ),
    ]
