# Generated by Django 3.2.16 on 2023-02-15 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_alter_usersetting_verification_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Active_don',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='id_youtube_ch',
            field=models.CharField(max_length=24, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='verification_expires',
            field=models.DateField(default=datetime.date(2023, 2, 18)),
        ),
    ]
