# Generated by Django 3.2.16 on 2023-02-25 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_adsvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adsvideo',
            old_name='miniature',
            new_name='image',
        ),
        migrations.AddField(
            model_name='adsvideo',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Image')], default='video', max_length=5),
        ),
        migrations.AddField(
            model_name='adsvideo',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='adsvideo',
            name='detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='adsvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videosAds'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='verification_expires',
            field=models.DateField(default=datetime.date(2023, 2, 28)),
        ),
    ]
