# Generated by Django 3.2.16 on 2023-02-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_auto_20230225_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_youtube_ch',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
