# Generated by Django 3.2.16 on 2023-02-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_alter_usersetting_verification_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_youtube_ch',
            field=models.CharField(default=False, max_length=24, null=True),
        ),
    ]
