# Generated by Django 3.2.16 on 2023-02-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0055_alter_user_id_youtube_ch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_youtube_ch',
            field=models.CharField(default='23454frSRGADEedsdRGV34', max_length=24, null=True),
        ),
    ]
