# Generated by Django 3.2.16 on 2023-02-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0060_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='stripe_access_token',
            new_name='stripe_account_holder_name',
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_routing_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
