# Generated by Django 3.2.16 on 2023-03-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0065_alter_usersetting_verification_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_youtube_ch',
            field=models.TextField(blank=True, default=''),
        ),
    ]
