# Generated by Django 3.2.16 on 2023-01-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='img',
            field=models.ImageField(blank=True, default='/static/images/ABLACKADABRA.png', null=True, upload_to='media/imagevid'),
        ),
        migrations.AlterField(
            model_name='video',
            name='vid',
            field=models.FileField(blank=True, default='/static/vidéos/video web.mp4', null=True, upload_to='media/videos'),
        ),
    ]
