# Generated by Django 3.2.16 on 2023-01-11 22:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('contenue', models.TextField()),
                ('date_added', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='img',
        ),
        migrations.AddField(
            model_name='video',
            name='comments',
            field=models.ManyToManyField(related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='filesvideo'),
        ),
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='miniature',
            field=models.ImageField(blank=True, null=True, upload_to='imagevid'),
        ),
        migrations.AddField(
            model_name='video',
            name='playlists',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='vid',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
