# Generated by Django 3.2.16 on 2023-01-11 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0002_auto_20230111_2311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
