# Generated by Django 3.2.16 on 2023-01-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0002_auto_20230104_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/imagevid'),
        ),
        migrations.AlterField(
            model_name='video',
            name='vid',
            field=models.FileField(blank=True, null=True, upload_to='media/videos'),
        ),
    ]
