# Generated by Django 3.2.16 on 2023-01-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0003_don'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
