# Generated by Django 3.2.16 on 2023-01-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0003_auto_20230104_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='img',
        ),
    ]
