# Generated by Django 3.2.16 on 2023-01-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0004_remove_video_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='vid',
        ),
    ]
