# Generated by Django 3.2.16 on 2023-01-11 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='comments',
            new_name='n_comments',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='likes',
            new_name='n_likes',
        ),
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='membre.video'),
        ),
    ]
