# Generated by Django 3.2.16 on 2023-01-12 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0006_alter_video_playlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
