# Generated by Django 3.2.16 on 2023-01-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0006_auto_20230104_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='vid',
        ),
    ]
