# Generated by Django 3.2.16 on 2023-01-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0007_remove_video_vid'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='vid',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='video',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='imagevid'),
        ),
    ]
