# Generated by Django 3.2.16 on 2023-01-12 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membre', '0007_video_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='abonnements',
            field=models.ManyToManyField(related_name='abonnements', to=settings.AUTH_USER_MODEL),
        ),
    ]
