# Generated by Django 3.2.16 on 2023-01-12 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membre', '0008_video_abonnements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='abonnements',
            field=models.ManyToManyField(blank=True, null=True, related_name='abonnements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='n_comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='n_likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
