# Generated by Django 3.2.16 on 2023-01-15 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0010_savedvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='abonnements',
        ),
    ]
