# Generated by Django 3.2.16 on 2023-01-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0011_videohistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='videohistory',
            name='time_paused',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
