# Generated by Django 3.2.16 on 2023-01-15 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membre', '0011_remove_video_abonnements'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='abonnements',
            field=models.ManyToManyField(blank=True, null=True, related_name='abonnements', to=settings.AUTH_USER_MODEL),
        ),
    ]
