# Generated by Django 3.2.16 on 2023-01-15 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0012_video_abonnements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='abonnements',
        ),
    ]
