# Generated by Django 3.2.16 on 2023-01-30 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membre', '0012_videohistory_time_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='don',
            name='to_user_don',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receveur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='don',
            name='user_don',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donneur', to=settings.AUTH_USER_MODEL),
        ),
    ]
