# Generated by Django 3.2.16 on 2023-01-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0015_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='cover_image',
            field=models.ImageField(default='static/images/logo muntube.png', upload_to='channels/cover_images/'),
        ),
    ]
