# Generated by Django 3.2.16 on 2023-01-31 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0016_alter_channel_cover_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
