# Generated by Django 3.2.16 on 2023-02-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0018_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
