# Generated by Django 3.2.16 on 2023-02-18 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_alter_usersetting_verification_expires'),
        ('membre', '0027_auto_20230216_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='play_lists',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.playlist'),
        ),
    ]
