# Generated by Django 3.2.16 on 2023-02-19 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0029_revendication'),
    ]

    operations = [
        migrations.AddField(
            model_name='revendication',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
