# Generated by Django 3.2.16 on 2023-02-20 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membre', '0030_revendication_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_channel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_channel', to=settings.AUTH_USER_MODEL),
        ),
    ]
