# Generated by Django 3.2.16 on 2023-02-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0032_subscriptionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_channel',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SubscriptionStatus',
        ),
    ]
