# Generated by Django 3.2.16 on 2023-02-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0034_report_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_comment',
            name='contenue',
            field=models.TextField(default=False),
        ),
    ]
