# Generated by Django 3.2.16 on 2023-02-22 17:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membre', '0036_report'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='Report_video',
        ),
    ]
