# Generated by Django 3.2.16 on 2023-02-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0038_auto_20230224_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(db_index=True, max_length=512),
        ),
    ]
