# Generated by Django 3.2.16 on 2023-03-01 22:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membre', '0041_alter_video_miniature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamations_Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout_don', models.IntegerField(default=10)),
                ('date_don', models.DateTimeField(default=datetime.datetime.today)),
                ('to_user_don', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receveur_rec', to=settings.AUTH_USER_MODEL)),
                ('user_don', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donneur_rec', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.video')),
            ],
        ),
    ]
