# Generated by Django 3.2.16 on 2023-03-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0043_saveddoc_savedlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedDoc',
        ),
    ]
